# Generated by Django 4.1.3 on 2022-11-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('caseImage', models.FileField(upload_to='caseImage')),
                ('caseName', models.CharField(max_length=25)),
                ('caseRate', models.IntegerField()),
            ],
            options={
                'db_table': 'CaseDetails',
            },
        ),
        migrations.CreateModel(
            name='DesignDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('DesignImage', models.FileField(upload_to='DesignImage')),
                ('DesignName', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'DesignDetails',
            },
        ),
        migrations.CreateModel(
            name='PhoneDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('PhoneName', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'PhoneDetails',
            },
        ),
    ]
