# Generated by Django 4.1.3 on 2022-11-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casemodels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designdetails',
            name='CaseName',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
